ToDo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from ToDo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.custom_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db import models

class UsernameValidator(ASCIIUsernameValidator):
    regex = r'^[\w-_]\Z'
    message = '영문자, 숫자, _, -만 사용가능합니다.'


class UserProfile(AbstractUser):
    username = models.CharField("아이디", max_length=36, unique=True)
    username_validator = UsernameValidator()
    email = models.EmailField("이메일", max_length=255)

    address = models.CharField("도로명주소", max_length=255, blank=True, null=True)
    birth_date = models.DateField("생년월일", blank=True, null=True)
    phone = models.CharField("연락처", max_length=18, blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from accounts.models import UserProfile


class AccountCreationForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'password1', 'password2', 'address', 'phone', 'birth_date']


class LoginForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

ToDo/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html', {
        'user': request.user,
    })

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import AccountCreationForm, LoginForm
from django.contrib.auth import login, authenticate


def custom_login(request):
    user = request.user
    if user.is_authenticated:
        return redirect(reverse('accounts:profile'))
    elif request.method == "POST":
        form = LoginForm(request.POST)
        user = authenticate(
            username=form['username'].value(),
            password=form['password'].value(),
        )
        if user is not None:
            login(request, user)
            return redirect(reverse('accounts:profile'))
        else:
            messages.add_message(request, messages.INFO, "아이디나 비밀번호를 다시 생각해보세요")

    return render(request, 'accounts/login.html', {
        'user': user,
        'form': LoginForm(),
    })


def register(request):
    user = request.user
    if user.is_authenticated:
        return redirect(reverse('accounts:profile'))

    if request.method == "POST":
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, '회원가입 성공')

            return redirect(reverse('accounts:login'))
        else:
            messages.add_message(request, messages.INFO, '회원가입 실패')
    else:
        form = AccountCreationForm()

    return render(request, 'accounts/register.html', {
        'user': user,
        'form': form,
    })


@login_required(login_url='/accounts/login/')
def profile(request):
    user = request.user
    return render(request, 'accounts/profile.html', {'user': user})

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}"/>
{% endblock %}
{% block content %}
    <form class="main-form" action="{% url 'accounts:login' %}" method="post" style="width: fit-content; margin: 0 auto;">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
                <span{% if message.tags %} class="{{ message.tags }} text-warning"{% endif %}>{{ message }}</span><br>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            <p>
                {{ field.label }}<br>
                {{ field }}<br>
            </p>
        {% endfor %}
        <input type="submit" value="로그인" />
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
    <h1>profile</h1>
    {{ user.get_username }}<br>
    {{ user.date_joined }}<br>
    {{ user.last_login }}
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}"/>
{% endblock %}
{% block content %}
    <form class="main-form" action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                <small class="text-warning">{{ field.errors }}</small><br>
                {{ field.label }}<br>
                {{ field }}<br>
                <small class="text-primary">{{ field.help_text }}</small>
            </p>
        {% endfor %}
        <input type="submit" value="회원가입" />
    </form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block meta %}
        {% endblock %}

        {% load static %}

        <link rel="shortcut icon" href="{% static '/favicon.ico' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/base.css' %}"/>
        {% block css %}
        {% endblock %}

        <title>ToDo</title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-light">
                <a href="{% url 'index' %}">
                    <img id="logo" src="{% static 'logo.png' %}" width="70" height="70"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbarSupportedContent" class="navbar-collapse collapse">
                    <ul class="navbar-nav justify-content-end d-flex flex-fill">
                        <li class="nav-item active">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                            {% else %}
                                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                            {% endif %}
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">마이페이지</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">회원가입</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">설정</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">고객센터</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <nav class="navbar navbar-expand-sm navbar-light">
                <form class="form-inline ml-auto" action="/action_page.php">
                    <input class="form-control mr-sm-2" type="text" placeholder="프로젝트 이름">
                    <button class="btn btn-success" type="submit">검색</button>
                </form>
            </nav>
        </header>

        <div id="content">
        {% block content %}
        {% endblock %}
        </div>

        <footer>

        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>index</h1>
{% endblock %}